#!/bin/sh
script_path=$(dirname "$(readlink -f "$0")")
version=$(grep -zo '<version>.*</ver.*\n.*<name>OpenFastTrace' pom.xml | sed -e's/[^0-9.]//g')

java -jar "$script_path/target/openfasttrace-$version.jar" $@