#!/bin/sh

set -o errexit
set -o nounset

script_path="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
version=$(grep -zo '<revision>.*</revision>' "$script_path"/parent/pom.xml | sed -e's/[^0-9.]//g')
jar_file="$script_path/product/target/openfasttrace-$version.jar"

if [ ! -f "$jar_file" ]; then
    echo "JAR file $jar_file not found."
    echo "Build it by running 'mvn package'"
    exit 1
fi

# shellcheck disable=SC2068 # Double quote to prevent globbing
java -jar "$jar_file" $@
