@startuml Context
!include ../../actors/quality_engineer.plantuml
!include ../../actors/developer.plantuml
!include ../../components/system.plantuml
!include ../../components/continuous_integration.plantuml

developer -left- system
quality_engineer -right- system
continuous_integration -up- system
@enduml