@startuml
!include ../clean.skin
class Importer
class SpecificationItemListBuilder
interface ImportEventListener <<interface>>

Importer -down-> ImportEventListener
SpecificationItemListBuilder -up-|> ImportEventListener
@enduml