@startuml
!include ../clean.skin

class ImporterFactoryLoader {
}

class java.util.ServiceLoader {
}

class MultiFileImporter {
}

class ImporterService {
    + ImporterService(context: ImporterContext) : ImporterService 
    + createImporter() : MultiFileImporter
}

interface Importer <<interface>> {
    + runImport() : void
}

class ZipFileImporter {
}

class ImporterFactory <<abstract>> {
    + init(context: ImporterContext) : void
    + supportsFile(inputFile: InputFile) : boolean
    + createImporter(inputFile: InputFile, listener: ImportEventListener) : Importer
    * getContext() : ImporterContext
}

class RegExMatchingImporterFactory <<abstract>> {
}

class ZipFileImporterFactory {
}

class ImporterContext {
    + getImporterService() : ImporterService
    + setImporterService(importerService: ImporterService) : void
}

ZipFileImporter .up.|> Importer
ZipFileImporterFactory -up-|> RegExMatchingImporterFactory
RegExMatchingImporterFactory -up-|> ImporterFactory
ZipFileImporterFactory -right-> ZipFileImporter : <<create>>
ImporterFactory -right-> ImporterContext : <<use>>
ImporterContext --> ImporterService : <<use>>
java.util.ServiceLoader --> ZipFileImporterFactory : <<create>>
ImporterFactoryLoader --> java.util.ServiceLoader : <<use>>
ImporterFactoryLoader --> ImporterFactory : <<initialize>>
ImporterService --> ImporterContext : <<create>>
ImporterService --> MultiFileImporter : <<create>>
@enduml