package openfasttrack.core;

public enum LinkStatus
{
    COVERS, UNWANTED, PREDATED, OUTDATED, AMBIGUOUS, DUPLICATE, ORPHANED, //
    COVERED_SHALLOW, COVERED_UNWANTED, COVERED_PREDATED, COVERED_OUTDATED
}
