name: Broken Links Checker

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      # The Autosar TLS certificate cannot be validated from GitHub Actions.
      - name: Configure broken links checker
        run: |
          mkdir -p ./target
          cat << 'EOF' > ./target/broken_links_checker.json
          {
            "aliveStatusCodes": [429, 200],
            "ignorePatterns": [
              {
                "pattern": "^https://www.autosar.org/"
              }
            ]
          }
          EOF
      - uses: tcort/github-action-markdown-link-check@e047c5b37f24ab722bbef1a27b6fab7f96bc4068
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "no"
          config-file: ./target/broken_links_checker.json
